[package]

name = "libz-sys"
version = "0.0.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = ["z"]
build = "build.rs"

[lib]
name = "libz-sys"
path = "lib.rs"

[build-dependencies]
pkg-config = "*"


