[package]

name = "openssl-sys"
version = "0.0.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = ["openssl"]
build = "build.rs"

[lib]
name = "openssl-sys"
path = "lib.rs"

[build-dependencies.pkg-config]
git = "https://github.com/alexcrichton/pkg-config-rs"
