[package]

name = "miniz-sys"
version = "0.0.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = ["miniz"]
build = "build.rs"

[build-dependencies]
gcc = "^1.2.0"

[lib]
name = "miniz-sys"
path = "lib.rs"
